### ISSUE TITLE
Trying to run (list index out of range)

### ISSUE THREAD

**Issue by plant7403** [yashgugale/PyTorch-Style-Transfer-On-Video#1]
```
root@ai-desktop:/work/PyTorch-Style-Transfer-On-Video# python3 "style transfer on video.py" 
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /root/.cache/torch/hub/checkpoints/vgg19-dcbb9e9d.pth
100.0%
Running on GPU
Traceback (most recent call last):
  File "style transfer on video.py", line 293, in <module>
    main()
  File "style transfer on video.py", line 283, in main
    convert_video_to_frames(sys.argv[1])	
IndexError: list index out of range
````

**Comment by plant7403** [comment]
I'm very sorry, my bad, forgot to add an argument for the input video :+1:
